- name: My First Playbook
  hosts: all
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message 
     ansible.builtin.debug:
      msg: Congratulations you have written your first playbook and it worked 

