---

- name: Copy multiple files
  hosts: shaka
  become: true
  tasks:
    - name: Copy files with specific owner, group, and permissions
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop:
        - { src: '/home/vhonani/Documents/omvl/olmvu_fe', dest: '/home/natisuser/apps/NaTIS/olmvu/debug/bundle/', owner: 'natisuser', group: 'natisuser', mode: '0755' }
        - { src: '/home/vhonani/Documents/omvl/data', dest: '/home/natisuser/apps/NaTIS/olmvu/debug/bundle/', owner: 'natisuser', group: 'natisuser', mode: '0755' }
        - { src: '/home/vhonani/Documents/omvl/lib', dest: '/home/natisuser/apps/NaTIS/olmvu/debug/bundle/', owner: 'natisuser', group: 'natisuser', mode: '0755' }

